export enum EnumRolUserFormation{
  PRESIDENT,DIRECTOR_MUSICAL,VOCALIST,TREASURER,ADMINISTRATOR,ARCHIVIST,ASSISTANCE_CONTROL,
  PERCUSSION,HAND_PERCUSSION_DE_MANO,KEYBOARD_INSTRUMENT,ELECTRONIC_INSTRUMENTS,PULSED_STRINGS,
  BOWED_STRINGS,WINDWOOD,BRASS_INSTRUMENTS
}
